In [1]:
import pandas as pd

In [2]:
s= pd.Series([1,2,3,4,5], index=["A","B","C","D","E"])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [3]:
data = [[1,444,"abc"],
         [2,222,"awe"],
         [3,333,"rgd"],
         [4,444,"kfk"]]

'''
 data = { "col1":[1,2,3,4],
        
         "col2":[444,222,333,444],
        
         "col3":["abc","awe","rgd","kfk"] }
        
'''

df = pd.DataFrame(data, columns= ["col1","col2","col3"])
df

   col1  col2 col3
0     1   444  abc
1     2   222  awe
2     3   333  rgd
3     4   444  kfk

In [5]:
df = pd.DataFrame([[1,444,"abc"],
         [2,222,"awe"],
         [3,333,"rgd"],
         [4,444,"kfk"]])

display(df)
columns = ["col1","col2","col3"]
df.columns=columns
display(df)
df.columns

   0    1    2
0  1  444  abc
1  2  222  awe
2  3  333  rgd
3  4  444  kfk

   col1  col2 col3
0     1   444  abc
1     2   222  awe
2     3   333  rgd
3     4   444  kfk

Index(['col1', 'col2', 'col3'], dtype='object')

In [6]:
df = pd.DataFrame([[1,444,"abc"],
         [2,222,"awe"],
         [3,333,"rgd"],
         [4,444,"kfk"]])

display(df)
index=["r1","r2","r3","r4"]
df.index=index
display(df)

   0    1    2
0  1  444  abc
1  2  222  awe
2  3  333  rgd
3  4  444  kfk

    0    1    2
r1  1  444  abc
r2  2  222  awe
r3  3  333  rgd
r4  4  444  kfk

In [7]:
df.dtypes

0     int64
1     int64
2    object
dtype: object

In [17]:
df = pd.DataFrame([[1,444,"abc"],
         [2,222,"awe"],
         [3,333,"rgd"],
         [4,444,"kfk"]])

display(df)
columns = ["col1","col2","col3"]
df.columns=columns
display(df)
df.columns
df["col3"].dtype

   0    1    2
0  1  444  abc
1  2  222  awe
2  3  333  rgd
3  4  444  kfk

   col1  col2 col3
0     1   444  abc
1     2   222  awe
2     3   333  rgd
3     4   444  kfk

dtype('O')

In [9]:
cols=["col1","col2"]
df[cols] = df[cols].astype("category")
df.dtypes

col1    category
col2    category
col3      object
dtype: object

In [10]:
df.head()

  col1 col2 col3
0    1  444  abc
1    2  222  awe
2    3  333  rgd
3    4  444  kfk

In [11]:
df.tail()

  col1 col2 col3
0    1  444  abc
1    2  222  awe
2    3  333  rgd
3    4  444  kfk

In [12]:
df.describe(include='category')

        col1  col2
count      4     4
unique     4     3
top        1   444
freq       1     2

In [13]:
df["col2"].nunique()

3

In [14]:
df["col2"].unique()

[444, 222, 333]
Categories (3, int64): [222, 333, 444]

In [18]:
df["col2"].min()

222

In [19]:
df["col2"].sum()

np.int64(1443)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      int64
 1   col2    4 non-null      int64
 2   col3    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes

In [21]:
df["col2"].value_counts()

col2
444    2
222    1
333    1
Name: count, dtype: int64